version: "3.9"

services:
  # Service pour votre API FastAPI
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"  # Port exposé pour l'API
    volumes:
      - ./Backend:/app/Backend  # Synchronisation des fichiers
    environment:
      - ENVIRONMENT=development  # Vous pouvez garder cette ligne pour ajouter des variables d'environnement si nécessaire
      
  keycloak-db:
      image: postgres
      container_name: keycloak-db
      env_file:
        - .env
      networks:
        - default
      ports:
        - "25432:5432"
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    ports:
      - 8080:8080
    restart: always

 
