version: "3.4"

services:
  keycloak-db:
      image: postgres
      container_name: keycloak-db
      env_file:
        - .env
      networks:
        - default
      ports:
        - "25432:5432"
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    ports:
      - 8080:8080
    restart: always

  
