version: "3.7"
services:
  kong-database:
    image: kong:3.0.0-alpine
    container_name: kong-database  # Nom personnalisé du conteneur
    restart: always
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
    ports:
      - "5432:5432"
    networks:
      - kong-net

  kong:
    image: kong:3.0.0-alpine
    container_name: kong-gateway  # Nom personnalisé du conteneur
    restart: always
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_GUI_HOST: "0.0.0.0"
    ports:
      - "8000:8000"  # API Gateway Proxy (HTTP)
      - "8443:8443"  # API Gateway Proxy (HTTPS)
      - "8001:8001"  # Admin API (gérer Kong)
    depends_on:
      - kong-database
    networks:
      - kong-net

  kong-migrations:
    image: kong:3.0.0-alpine
    container_name: kong-migrations  # Nom personnalisé du conteneur
    command: "kong migrations bootstrap"
    depends_on:
      - kong-database
    networks:
      - kong-net
    restart: "no"

networks:
  kong-net:
    driver: bridge
